### ISSUE TITLE
A lot of Queue for Zabbix active

### ISSUE THREAD

**Issue by Onc3k** [zbx-sadman/unifi_miner#14]
Hi,

we using your solution a long time, now we builded new environment with DB cluster, proxysql and two zabbix servers with pacemaker and corosync. Together with the environment upgrade I did upgrade zabbix to version 4.4.1 and on the new environment I have problem with a lot of Queue for Active checks. I tryed change zabbix agent and zabbix server settings like buffer, pollers etc. and nothing helped me. Could you please make update of this template or do you have any advice for me or someone? Thanks a lot.

PS: on old environment was zabbix on 4.2.x version and all worked fine.

**Comment by zbx-sadman** [comment]
Hello

My perl scripts / templates does not contain any specific things for Zabbix 4.2 or Zabbix 4.4. 

I guess that is Zabbix's Active mode issue. Do you analyzed logs of agent on UniFi host (where script is placed)?

**Comment by Onc3k** [comment]
Hello,

I tryed debug and in logs wasn't any error or problems. All is same like before environment upgrade. It just look like zabbix agent isn't able to solve all active checks in normal time, but I don't know why...

**Comment by Onc3k** [comment]
![image](https://user-images.githubusercontent.com/57482834/68593129-09d7d780-0495-11ea-9345-9a6aedd80044.png)

**Comment by Onc3k** [comment]
I tryed switch Zabbix agent active to passive and after this was Zabbix server overloaded. Tryed all possible settings for zabbix_agent and no changes, mysql was tunned. I don't have any idea now. Whole environment is more powerfull then before and it have these problems.

**Comment by zbx-sadman** [comment]
> I tryed debug and in logs wasn't any error or problems. All is same like before environment upgrade. It just look like zabbix agent isn't able to solve all active checks in normal time, but I don't know why...

Yes, Zabbix agent was used (at least in 2.x, & 3.x branches) single thread for all Active Checks. And it can skips some item check if previous item check run very long.

Unfortunately, i can't say anymore without some investigation of affected system.

But you can take UniFi Proxy and give a rest for your overloaded host.

**Comment by Onc3k** [comment]
`But you can take UniFi Proxy and give a rest for your overloaded host.`

Pls, what do you mean here?

**Comment by zbx-sadman** [comment]
> `But you can take UniFi Proxy and give a rest for your overloaded host.`
> 
> Pls, what do you mean here?

https://github.com/zbx-sadman/unifi_proxy
