### ISSUE TITLE
Use of uninitialized value in string at /usr/bin/unifi_miner.pl line 1070

### ISSUE THREAD

**Issue by velthal** [zbx-sadman/unifi_miner#16]
Привет! есть проблема с запуском скрипта. 
версия контроллера 5.11

данные по 
unifi.proxy[discovery,uap] заббикс получает нормально

> zabbix_agentd -t unifi.proxy[discovery,uap,,vap_table]
> unifi.proxy[discovery,uap,,vap_table]         [t|Use of uninitialized value in string at /usr/bin/unifi_miner.pl line 1070.

> zabbix_agentd -t unifi.proxy[discovery,uap,,vwire_vap_table]
> unifi.proxy[discovery,uap,,vwire_vap_table]   [t|Use of uninitialized value in string at /usr/bin/unifi_miner.pl line 1057

**Comment by zbx-sadman** [comment]
Hello


```
unifi# zabbix_agentd -t unifi.proxy.test[discovery,uap,,vap_table] | more
unifi.proxy.test[discovery,uap,,vap_table]    [t|{
   "data" : [
      {
         "{#UAPMAC}" : "00:27:22:xx:xx:xx",
         "{#SITEID}" : "5523f87e99320d293df816fd",
         "{#ESSID}" : "xxxxxx",
         "{#UP}" : "1",
         "{#STATE}" : "RUN",
         "{#SITEDESC}" : "Default",
         "{#UAPNAME}" : "xxxxxxxx",
         "{#SITENAME}" : "default",
         "{#UAPID}" : "5523ff3a9932508ffaf3b433",
         "{#ID}" : "5d9da571b9dd4a0ba27135e1"
      },
      {
         "{#UAPMAC}" : "00:27:22:xx:xx:xx",
         "{#SITEID}" : "5523f87e99320d293df816fd",
         "{#ESSID}" : "xxxxxxx",
         "{#UP}" : "1",
         "{#STATE}" : "RUN",
         "{#SITEDESC}" : "Default",
         "{#UAPNAME}" : "xxxxxx",
         "{#SITENAME}" : "default",
         "{#UAPID}" : "5523ff3a9932508ffaf3b433",
         "{#ID}" : "5523fa2e9932508ffaf3b3fc"
      },
...

```

**Comment by velthal** [comment]
> $ zabbix_agentd -t unifi.proxy[discovery,uap,,vap_table]
> unifi.proxy[discovery,uap,,vap_table]         [t|Use of uninitialized value in string at /usr/bin/unifi_miner.pl line 1070.
> Use of uninitialized value in string at /usr/bin/unifi_miner.pl line 1070.
> Use of uninitialized value in string at /usr/bin/unifi_miner.pl line 1070.
> Use of uninitialized value in string at /usr/bin/unifi_miner.pl line 1070.
> [27925] 2019-12-04 10:39:54 [+] fetchData() started
> [27925] 2019-12-04 10:39:54 [+] fetchDataFromController() started
> [27925] 2019-12-04 10:39:54 [>]	 args: object path: 'https://127.0.0.1:8443/api/self/sites'
> [27925] 2019-12-04 10:39:54 [.]		Try to log in into controller...
> [27925] 2019-12-04 10:39:55 [.]		Login successfull
> [27925] 2019-12-04 10:39:55 [-] fetchData() finished
> [27925] 2019-12-04 10:39:55 [+] fetchData() started
> [27925] 2019-12-04 10:39:55 [+] fetchDataFromController() started
> [27925] 2019-12-04 10:39:55 [>]	 args: object path: 'https://127.0.0.1:8443/api/s/default/stat/device'
> [27925] 2019-12-04 10:39:55 [.]		Try to log in into controller...
> [27925] 2019-12-04 10:39:55 [.]		Login successfull
> [27925] 2019-12-04 10:39:55 [-] fetchData() finished
> [27925] 2019-12-04 10:39:55 [*]		 Key given: vap_table
> [27925] 2019-12-04 10:39:55 [+] getMetric() started
> [27925] 2019-12-04 10:39:55 [>]	 args: key: 'vap_table', action: 'discovery'
> [27925] 2019-12-04 10:39:55 [-] getMetric() finished 
> [27925] 2019-12-04 10:39:55 [+] addToLLD() started
> [27925] 2019-12-04 10:39:55 [-] addToLLD() finished
> [27925] 2019-12-04 10:39:55 [*] Logout from UniFi controller
> {
>    "data" : [
>       {
>          "{#UAPID}" : "5c483aa4a8bdb908e8cb6701",
>          "{#UP}" : "1",
>          "{#UAPMAC}" : "f0:9f:c2:xx:xx:xx",
>          "{#ID}" : "5c6bc76ba8bdb90a7989dd5b",
>          "{#SITEDESC}" : "office",
>          "{#STATE}" : "RUN",
>          "{#ESSID}" : "xx",
>          "{#SITEID}" : "5c482cef99c87020de41d7a6",
>          "{#UAPNAME}" : "",
>          "{#SITENAME}" : "default"
>       },
>       {
>          "{#SITENAME}" : "default",
>          "{#SITEID}" : "5c482cef99c87020de41d7a6",
>          "{#UAPNAME}" : "",
>          "{#ESSID}" : "xxxxxxxx",
>          "{#SITEDESC}" : "office",
>          "{#ID}" : "5c48327399c87020de41d7be",
>          "{#STATE}" : "RUN",
>          "{#UAPID}" : "5c483aa4a8bdb908e8cb6701",
>          "{#UAPMAC}" : "f0:9f:c2:79:7e:40",
>          "{#UP}" : "1"
>       },
>       {
>          "{#SITEID}" : "5c482cef99c87020de41d7a6",
>          "{#UAPNAME}" : "",
>          "{#SITENAME}" : "default",
>          "{#UAPMAC}" : "f0:9f:c2:79:7e:40",
>          "{#UP}" : "1",
>          "{#UAPID}" : "5c483aa4a8bdb908e8cb6701",
>          "{#STATE}" : "RUN",
>          "{#ID}" : "5c6bc76ba8bdb90a7989dd5b",
>          "{#SITEDESC}" : "office",
>          "{#ESSID}" : "GP"
>       },
>       {
>          "{#SITENAME}" : "default",
>          "{#SITEID}" : "5c482cef99c87020de41d7a6",
>          "{#UAPNAME}" : "",
>          "{#ESSID}" : "vpsecpoint",
>          "{#ID}" : "5c48327399c87020de41d7be",
>          "{#SITEDESC}" : "office",
>          "{#STATE}" : "RUN",
>          "{#UAPID}" : "5c483aa4a8bdb908e8cb6701",
>          "{#UP}" : "1",
>          "{#UAPMAC}" : "f0:9f:c2:79:7e:40"
>       }
>    ]
> }]
> 
сайта default у меня нет

**Comment by zbx-sadman** [comment]
default всегда есть. Во всяком случае - был во всех релизах, которые я ставил.

Вобщем, надо посмотреть внутрь JSON-а UAP:  `./unifi_miner.pl -a raw -o uap -i "f0:9f:c2:79:7e:40" -k "*" > f0uap.txt`. У меня такое чувство, что объекты массива `vap_table` потеряли ключ `name`

**Comment by velthal** [comment]
[f0uap.txt](https://github.com/zbx-sadman/unifi_miner/files/3921191/f0uap.txt)

ещё вопрос, в самом скрипте я в значения string пользователяи пароля вписал данные в открытом виде. это же не порушит скрипт?

**Comment by velthal** [comment]
начал игнорировать вывод ошибок, стали поступать данные по пассивным проверкам. но не все. средний сигнал на клиента почему-то неалё :( 
![photo_2019-12-04_17-13-11](https://user-images.githubusercontent.com/36160317/70149551-65266f80-16b9-11ea-92f6-d961e3667224.jpg)
