### ISSUE TITLE
Странная работа фильтров

### ISSUE THREAD

**Issue by a7lan** [zbx-sadman/unifi_miner#17]
Делаю
```unifi_miner.pl -a get -o user -k [rssi=28].ip -c 1```
результат
192.168.1.112

делаю 
```unifi_miner.pl -a get -o user -k [rssi>27].ip -c 1```
В выводе пусто. 

Вообще знак больше и меньше у меня не работает. Равно и не равно выводит значения.

**Comment by zbx-sadman** [comment]
unifi# ./unifi_miner.pl -a get -o user -k [rssi>2].ip

unifi# ./unifi_miner.pl -a get -o user -k "[rssi>2].ip"
192.168.0.115

**Comment by a7lan** [comment]
Спасибо.  Не учел этот момент.
