### ISSUE TITLE
Special characters in zabbix keys are not supported

### ISSUE THREAD

**Issue by damago1** [zbx-sadman/unifi_miner#5]
I have installed both the perl script and the zabbix templates.
Unfortunately they do not work. 
The autodiscovery is generating keys like:

unifi.proxy[get,network,kvraj6sw,"[_id=58bb88aee4b0e875087b023d].purpose"]

which are not supported by Zabbix because you cannot include " and especially [ and ] in key.

**Comment by zbx-sadman** [comment]
Zabbix manual:

> Unless UnsafeUserParameters agent daemon configuration option is enabled, it is not allowed to pass flexible parameters containing these symbols: \ ' ” ` * ? [ ] { } ~ $ ! & ; ( ) < > | # @. Additionally, newline is not allowed either.

Also this situation is described in Troubleshooting section of UniFi Miner manual: https://github.com/zbx-sadman/unifi_miner/wiki/UniFi-Miner-guide-in-English.

Note, that you must setup zabbix agent to make able it work in active mode before use template which based on active checks.
