### ISSUE TITLE
Still show data of deleted UAPs

### ISSUE THREAD

**Issue by martinonicolas** [zbx-sadman/unifi_miner#7]
Hi, I Have a v5 Unifi controller with 4 UAPs conected. unifi_miner give me the correct answer when I search the amount of active UAPs ( ./unifi_miner.pl -a count -o uap -k "[state=1].state")  and/or (./unifi_miner.pl  -a sum -o uap -s default -k adopted). 

But after I delete one UAP from the controller the discovery option still show me 4 UAPs connected to the controller. And show me the erased UAP at state=0  as it's disconected...

To compare this result I use https://github.com/malle-pietje/UniFi-API-browser and it show me the correct values.. (3 managed UAPs and 0 Disconected)

Thanks!

**Comment by zbx-sadman** [comment]
At first - try use _-c 0_ option to say Miner "use no cache". If it help to get right results - just decrease cache lifetime or do not rush so much.

On fail - you need to analyze cache file and looking for difference betweem JSON-objects of deleted and normal UAPs.

Just now i have used  "Forget this UAP" button on v4 Controller and Miner show to me less number of records in LLD  -JSON (_-a discovery_ option).

**Comment by martinonicolas** [comment]
Thanks! It seams that if I use `-l https://127.0.0.1:8443` the controller check from de cache. As you said, I have to use `-c 0`  to get the current values.

In spite of this I realized that if I use `-l https://lan_ip:8443` I don't need to use `-c 0`. It seems that do not check the cache if you use de lan_ip. 

Thanks a lot!

**Comment by zbx-sadman** [comment]
No any special handling for localhost or any other IP exists in the code. 

Cache files for _localhost_ may be owned by root / other non-zabbix account  as a result of manual Miner running. In this case  it is enough to clear cache dir or just reboot (if cache placed on RAM-disk) to get Miner works properly.
