### ISSUE TITLE
Import Template UBNT_UNIFI_Controller Zabbix 3.2

### ISSUE THREAD

**Issue by LFPSGS** [zbx-sadman/unifi_miner#8]
Hi guys! I was following Sadman's instructions to install the miner and reading the issue with Windows Controllers. That said, I manage to make it work, but can't import the template on Zabbix (3.2.6). First I needed to change the max_upload_size on Zabbix, but now Iam getting this error:

"Cannot read XML: (41) Specification mandate value for attribute data-pjax-transient [Line: 35 | Column: 40]."

I'm not a programmer but I guess it has to do with Zabbix validations on XML file.

Can someone help?

Best Regards,
Luiz

**Comment by zbx-sadman** [comment]
Hello Luiz

Try to save template file from RAW view: 
https://raw.githubusercontent.com/zbx-sadman/unifi_proxy/master/Zabbix_Templates/UniFi%20Proxy%201.3.0/zbx_v2_4_Template_UBNT_UniFi_Controller_v_4_for_UniFi_Proxy.xml

**Comment by LFPSGS** [comment]
Thanks Sadman! That did the trick! :-D
