### ISSUE TITLE
Some data but not all

### ISSUE THREAD

**Issue by LFPSGS** [zbx-sadman/unifi_miner#9]
Hi Sadman! I'm trying to solve this mistery for a couple days now.  Iam using Zabbix 3.2.6 with a Windows UBNT Controller and following your instructions I was happy to tell that it worked, the LLD created itens, triggers and graphs for every AP that I have, but, the only itens Iam receiving data on Zabbix is the ICMP, Clients connected and Users Connected. 

Shouldn't I receive all data at this point? And since no data is comming from a lot of itens, the queue grows and the cache runs low.

Could u help me once again?

Best regards,
Luiz

**Comment by zbx-sadman** [comment]
Hello.

Do you not forget to set up Zabbix Agent (to which Unifi Miner "connected") to work in Active mode? Just change any "losted" Item's Type from Zabbix Agent (active)  to Zabbix Agent for fast check.

And may be Active Zabbix Agent scheme is not good for your configuration... Active checks is prefer for Agent, that placed on Unifi Controller's host.

**Comment by LFPSGS** [comment]
Indeed, once again you're right! :-D Works like a charm! Thanks sadman!
